config {
  type: "view",
  schema: dataform.projectConfig.vars.TARGET_DATA,
  description: "View for importing Vertex AI Search for Media (VAIS:M) Documents",
  dependOnDependencyAssertions: true,
  assertions: {
    uniqueKey: ["id"]
  },
  tags: ["VAISM"]
}


SELECT
    id
  , schemaId
  , parentDocumentId
  , jsonData
FROM ${ ref({ schema: dataform.projectConfig.vars.TARGET_DATA, name: "vaism_documents" }) }
