config {
  hasOutput: true,
  type: "operations",
  schema: dataform.projectConfig.vars.RAW_DATA,
  tags: ["LOAD_EXPORTS"]
}


LOAD DATA OVERWRITE ${ self() }
(
    id             INT64    NOT NULL
  , name           STRING
)
FROM FILES (
  format = "JSON",
  hive_partition_uri_prefix = "gs://${ dataform.projectConfig.vars.LOAD_GCS_BUCKET }/",
  uris = ["gs://${ dataform.projectConfig.vars.LOAD_GCS_BUCKET }/export_date*/company_ids.json"]
)
WITH PARTITION COLUMNS;